#!/bin/bash
profile_d_()
{
	cat << EOF >> /root/.bashrc
for i in /etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        . $i
    fi
done
EOF

cat << EOF >> /home/*/.bashrc
for i in /etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        . $i
    fi
done
EOF
}
profile_d_
