#!/bin/bash

check_root_()
{
	if [ "$EUID" -ne 0 ]
	  then echo "Please run as root"
	  exit
	fi
}

check_arch_and_deb_release_()
{
    if [ $(dpkg --print-architecture) = "amd64" ]; then
		echo "OK: computer system architecture is $ARCHITECTURE."
	else
		CONTINUE=0
		echo "ERROR: computer system architecture is not amd64."
		echo -e "\tcomputer system architecture is $ARCHITECTURE"
	fi

    if [ $(lsb_release -sc) = "bullseye" ]; then
		echo "OK: debian distribution is $DEB_CODENAME."
	else
		CONTINUE=0
		echo "ERROR: debian distribution codename is not bullseye nor buster."
		echo -e "\tdebian distribution codename is $DEB_CODENAME"
	fi
}

leave_()
{
	echo -e "\nleaving..."
	exit 2
}

initial_config_()
{
    ## export folders to path - IMPORTANT
    echo "export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin" >> /root/.bashrc
    source /root/.bashrc
    
    mkdir --parents /opt/software
    
    ## ntp client configuration
    FILE_=/etc/systemd/timesyncd.conf
    cp $FILE_ $FILE_.original
    cat << EOF > $FILE_
[Time]
NTP=pool.ntp.org
FallbackNTP=
RootDistanceMaxSec=5
PollIntervalMinSec=32
PollIntervalMaxSec=1024
EOF

    ## profile.d scripts to root user at /home
	cat << EOF >> /root/.bashrc
for i in /etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        . $i
    fi
done
EOF
    source /root/.bashrc

    ## profile.d scripts to every non root user
for f in $(ls /home/); do
    cat << EOF >> /home/$f/.bashrc
for i in /etc/profile.d/*.sh ; do
    if [ -r "$i" ]; then
        . $i
    fi
done
EOF
done
}

debian_packages_()
{
    bash ./packages
}

third_party_software_()
{
    for s in $(ls *.sh); do
        bash $s
    done
}

check_root_

initial_config_

debian_packages_

third_party_software_
